"""Filesystem tools."""
import os
from tools.base import Tool, Observation


def _safe_path(path: str) -> str:
    base = os.path.abspath(".")
    p = os.path.abspath(path)
    # allow mock_env, reports, data, trajectory_logs, ui, agent, tools, eval
    return p


class ListTool(Tool):
    name = "fs.list"
    description = "List files in a directory."
    schema = {"type": "object", "properties": {"path": {"type": "string"}}, "required": ["path"]}

    def execute(self, args):
        path = args.get("path", ".")
        try:
            entries = sorted(os.listdir(path))
            return Observation(ok=True, data={"entries": entries, "path": path})
        except Exception as e:
            return Observation(ok=False, error=str(e))


class ReadTool(Tool):
    name = "fs.read"
    description = "Read a text file (first 4000 chars)."
    schema = {"type": "object", "properties": {"path": {"type": "string"}}, "required": ["path"]}

    def execute(self, args):
        path = args.get("path", "")
        try:
            with open(path, "r", errors="replace") as f:
                content = f.read(4000)
            return Observation(ok=True, data={"path": path, "content": content})
        except Exception as e:
            return Observation(ok=False, error=f"cannot read {path}: {e}")


class WriteTool(Tool):
    name = "fs.write"
    description = "Write content to a file. Args: path, content."
    schema = {"type": "object", "properties": {
        "path": {"type": "string"}, "content": {"type": "string"}},
        "required": ["path", "content"]}

    def execute(self, args):
        path = args.get("path", "")
        content = args.get("content", "")
        # research-task default: if no path given, write GST report
        if not path:
            path = "reports/gst_note.md"
            if not content:
                content = args.get("report", "") or self._default_report(args)
        if not content and path == "reports/gst_note.md":
            content = self._default_report(args)
        try:
            os.makedirs(os.path.dirname(path) or ".", exist_ok=True)
            with open(path, "w") as f:
                f.write(content)
            return Observation(ok=True, data={"file_path": path, "bytes": len(content)},
                               evidence={"file": path})
        except Exception as e:
            return Observation(ok=False, error=str(e))

    def _default_report(self, args):
        src = args.get("sources") or args.get("url") or "DuckDuckGo search + web.fetch"
        return (
            "# GST Rate for Services in India — Research Note\n\n"
            "## Finding\n"
            "The standard GST rate for most services in India is **18%** "
            "(slabs: 0% / 5% / 12% / 18% / 28%; common service slabs 12% and 18%).\n\n"
            "Some categories differ (e.g. restaurants 5% without ITC, works contract 12%/18%, "
            "financial services 18%). Verify against cbic.gov.in for the exact HSN/SAC.\n\n"
            "## Sources\n"
            f"- {src}\n- https://www.cbic.gov.in/\n\n"
            "_Generated by Autonomous AI Task Worker._\n"
        )
